# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from acoustid_legacy_search.index.proto import index_pb2 as index__pb2


class IndexStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetIndex = channel.unary_unary(
                '/Acoustid.Server.PB.Index/GetIndex',
                request_serializer=index__pb2.GetIndexRequest.SerializeToString,
                response_deserializer=index__pb2.GetIndexResponse.FromString,
                )
        self.CreateIndex = channel.unary_unary(
                '/Acoustid.Server.PB.Index/CreateIndex',
                request_serializer=index__pb2.CreateIndexRequest.SerializeToString,
                response_deserializer=index__pb2.CreateIndexResponse.FromString,
                )
        self.DeleteIndex = channel.unary_unary(
                '/Acoustid.Server.PB.Index/DeleteIndex',
                request_serializer=index__pb2.DeleteIndexRequest.SerializeToString,
                response_deserializer=index__pb2.DeleteIndexResponse.FromString,
                )
        self.GetDocument = channel.unary_unary(
                '/Acoustid.Server.PB.Index/GetDocument',
                request_serializer=index__pb2.GetDocumentRequest.SerializeToString,
                response_deserializer=index__pb2.GetDocumentResponse.FromString,
                )
        self.GetAttribute = channel.unary_unary(
                '/Acoustid.Server.PB.Index/GetAttribute',
                request_serializer=index__pb2.GetAttributeRequest.SerializeToString,
                response_deserializer=index__pb2.GetAttributeResponse.FromString,
                )
        self.BulkUpdate = channel.unary_unary(
                '/Acoustid.Server.PB.Index/BulkUpdate',
                request_serializer=index__pb2.BulkUpdateRequest.SerializeToString,
                response_deserializer=index__pb2.BulkUpdateResponse.FromString,
                )
        self.Search = channel.unary_unary(
                '/Acoustid.Server.PB.Index/Search',
                request_serializer=index__pb2.SearchRequest.SerializeToString,
                response_deserializer=index__pb2.SearchResponse.FromString,
                )


class IndexServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAttribute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BulkUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IndexServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIndex,
                    request_deserializer=index__pb2.GetIndexRequest.FromString,
                    response_serializer=index__pb2.GetIndexResponse.SerializeToString,
            ),
            'CreateIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateIndex,
                    request_deserializer=index__pb2.CreateIndexRequest.FromString,
                    response_serializer=index__pb2.CreateIndexResponse.SerializeToString,
            ),
            'DeleteIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteIndex,
                    request_deserializer=index__pb2.DeleteIndexRequest.FromString,
                    response_serializer=index__pb2.DeleteIndexResponse.SerializeToString,
            ),
            'GetDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDocument,
                    request_deserializer=index__pb2.GetDocumentRequest.FromString,
                    response_serializer=index__pb2.GetDocumentResponse.SerializeToString,
            ),
            'GetAttribute': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAttribute,
                    request_deserializer=index__pb2.GetAttributeRequest.FromString,
                    response_serializer=index__pb2.GetAttributeResponse.SerializeToString,
            ),
            'BulkUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.BulkUpdate,
                    request_deserializer=index__pb2.BulkUpdateRequest.FromString,
                    response_serializer=index__pb2.BulkUpdateResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=index__pb2.SearchRequest.FromString,
                    response_serializer=index__pb2.SearchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Acoustid.Server.PB.Index', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Index(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Acoustid.Server.PB.Index/GetIndex',
            index__pb2.GetIndexRequest.SerializeToString,
            index__pb2.GetIndexResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Acoustid.Server.PB.Index/CreateIndex',
            index__pb2.CreateIndexRequest.SerializeToString,
            index__pb2.CreateIndexResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Acoustid.Server.PB.Index/DeleteIndex',
            index__pb2.DeleteIndexRequest.SerializeToString,
            index__pb2.DeleteIndexResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Acoustid.Server.PB.Index/GetDocument',
            index__pb2.GetDocumentRequest.SerializeToString,
            index__pb2.GetDocumentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAttribute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Acoustid.Server.PB.Index/GetAttribute',
            index__pb2.GetAttributeRequest.SerializeToString,
            index__pb2.GetAttributeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BulkUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Acoustid.Server.PB.Index/BulkUpdate',
            index__pb2.BulkUpdateRequest.SerializeToString,
            index__pb2.BulkUpdateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Acoustid.Server.PB.Index/Search',
            index__pb2.SearchRequest.SerializeToString,
            index__pb2.SearchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
